In [17]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])  #1D matrix
print(x)

[1 2 3 4 5]


In [3]:
x2 = np.array([[1,2],[5,6]]) #2D matrix
print(x)

[1 2 3 4 5]


In [4]:
print(x.shape)
print(x2.shape)
print(x.ndim)
print(x2.ndim)

(5,)
(2, 2)
1
2


In [6]:
a = np.arange(-5,6,.5)
print(a)
print(a.shape)
print(a.size)

[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5
  2.   2.5  3.   3.5  4.   4.5  5.   5.5]
(22,)
22


In [7]:
b = np.linspace(1,10,50)
print(b)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [9]:
c = np.random.random((3,3))
print(c)
print(c.shape)
print(c.size)

[[0.26917863 0.24056708 0.58230598]
 [0.49362944 0.69818479 0.44032241]
 [0.63958538 0.2823533  0.85640175]]
(3, 3)
9


In [10]:
d = np.random.randn(3,3)
print(d)
print(d.shape)
print(d.size)

[[-0.81929821 -1.41411985 -0.51275855]
 [-0.59865757 -1.00699053 -0.98250124]
 [ 0.47863908  1.39469955 -1.4241049 ]]
(3, 3)
9


In [11]:
e = np.random.randint(1,10,(3,3,3))
print(e)
print(e.shape)
print(e.size)

[[[3 6 9]
  [6 7 8]
  [5 2 5]]

 [[9 5 8]
  [4 7 3]
  [4 2 5]]

 [[2 2 9]
  [7 1 8]
  [2 9 7]]]
(3, 3, 3)
27


In [12]:
f= np.linspace(1,100,90)
print(f.shape)

(90,)


In [14]:
f2 = f.reshape(3,30)
print(f2)


[[  1.           2.11235955   3.2247191    4.33707865   5.4494382
    6.56179775   7.6741573    8.78651685   9.8988764   11.01123596
   12.12359551  13.23595506  14.34831461  15.46067416  16.57303371
   17.68539326  18.79775281  19.91011236  21.02247191  22.13483146
   23.24719101  24.35955056  25.47191011  26.58426966  27.69662921
   28.80898876  29.92134831  31.03370787  32.14606742  33.25842697]
 [ 34.37078652  35.48314607  36.59550562  37.70786517  38.82022472
   39.93258427  41.04494382  42.15730337  43.26966292  44.38202247
   45.49438202  46.60674157  47.71910112  48.83146067  49.94382022
   51.05617978  52.16853933  53.28089888  54.39325843  55.50561798
   56.61797753  57.73033708  58.84269663  59.95505618  61.06741573
   62.17977528  63.29213483  64.40449438  65.51685393  66.62921348]
 [ 67.74157303  68.85393258  69.96629213  71.07865169  72.19101124
   73.30337079  74.41573034  75.52808989  76.64044944  77.75280899
   78.86516854  79.97752809  81.08988764  82.20224719  83.314

boolean filtering

In [19]:
data=np.random.randint(1,1000, (5,5))
print(data)

[[893 557 420 351 220]
 [387 559 481  45 756]
 [241 299 337 593  33]
 [121 806 907 574 977]
 [484 530 930 680 656]]


In [20]:
for i in data:
    for j in i:
        if j<500:
            print(j,end=' ')

420 351 220 387 481 45 241 299 337 33 121 484 

In [21]:
data < 500

array([[False, False,  True,  True,  True],
       [ True, False,  True,  True, False],
       [ True,  True,  True, False,  True],
       [ True, False, False, False, False],
       [ True, False, False, False, False]])

In [22]:
data[data<500]

array([420, 351, 220, 387, 481,  45, 241, 299, 337,  33, 121, 484])

In [23]:
data[ (data<100) | (data>500)]

array([893, 557, 559,  45, 756, 593,  33, 806, 907, 574, 977, 530, 930,
       680, 656])